workflows:
  ios-debug:
    name: iOS debug build (AR engine patch)
    environment:
      flutter: stable          # or pin: 3.22.1 etc.
      xcode: latest
    scripts:
      # 1️⃣ Get Flutter deps
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      # 2️⃣ 🩹 Drop a minimal podspec so CocoaPods can see the plugin
      - name: Patch ar_flutter_plugin_engine podspec
        script: |
          PLUGIN_SYMLINK=".symlinks/plugins/ar_flutter_plugin_engine/ios"
          mkdir -p "$PLUGIN_SYMLINK"
          PODSPEC="$PLUGIN_SYMLINK/ar_flutter_plugin_engine.podspec"
          if [ ! -f "$PODSPEC" ]; then
            cat <<'SPEC' > "$PODSPEC"
  Pod::Spec.new do |s|
  s.name             = 'ar_flutter_plugin_engine'
  s.version          = '1.0.1'
  s.summary          = 'ARKit/ARCore Flutter plugin (engine fork)'
  s.homepage         = 'https://pub.dev/packages/ar_flutter_plugin_engine'
  s.license          = { :type => 'MIT' }
  s.author           = { :name => 'Community' }
  s.source           = { :path => '.' }
  s.source_files     = 'Classes/**/*.{h,m,mm,swift}'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency       'Flutter'
  s.platform         = :ios, '12.0'
  end
  SPEC
  fi

# 3️⃣ Run CocoaPods
- name: CocoaPods install
  script: |
    cd ios
    pod install --repo-update
    cd ..

# 4️⃣ Build the app (no automatic codesign)
- name: Flutter build iOS
  script: |
    flutter build ios --debug --no-codesign

artifacts:
  - build/ios/iphoneos/**/*.app
  - build/ios/iphoneos/**/*.ipa
