workflows:
  ios-debug:
    name: iOS debug build (patch AR engine)
    environment:
      flutter: stable         # or pin: 3.22.x, etc.
      xcode: latest

    scripts:
      # 1️⃣ Clean & get Flutter packages
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      # 2️⃣ 🩹  Create podspec for ar_flutter_plugin_engine
      - name: Patch ar_flutter_plugin_engine podspec
        script: |
          set -e

          # ----- locate pub-cache copy of the plugin -----
          CACHE_DIR=$(find "$HOME/.pub-cache" -type d -name "ar_flutter_plugin_engine-*" | head -n 1)
          echo "Plugin cache dir: $CACHE_DIR"
          mkdir -p "$CACHE_DIR/ios"

          PODSPEC_PATH="$CACHE_DIR/ios/ar_flutter_plugin_engine.podspec"

          # ----- write podspec only once -----
          if [ ! -f "$PODSPEC_PATH" ]; then
            printf '%s\n' \
              "Pod::Spec.new do |s|" \
              "  s.name    = 'ar_flutter_plugin_engine'" \
              "  s.version = '1.0.1'" \
              "  s.summary = 'ARKit/ARCore Flutter plugin (engine fork)'" \
              "  s.homepage= 'https://pub.dev/packages/ar_flutter_plugin_engine'" \
              "  s.license = { :type => 'MIT' }" \
              "  s.author  = { :name => 'Community' }" \
              "  s.source  = { :path => '.' }" \
              "  s.source_files = 'Classes/**/*.{h,m,mm,swift}'" \
              "  s.public_header_files = 'Classes/**/*.h'" \
              "  s.dependency 'Flutter'" \
              "  s.platform = :ios, '12.0'" \
              "end" > "$PODSPEC_PATH"
          fi

          # ----- copy into .symlinks folder (rebuilt by Flutter) -----
          SYMLINK_DIR="ios/.symlinks/plugins/ar_flutter_plugin_engine/ios"
          mkdir -p "$SYMLINK_DIR"
          cp -f "$PODSPEC_PATH" "$SYMLINK_DIR/"

      # 3️⃣ CocoaPods install
      - name: CocoaPods install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 4️⃣ Build (no codesign in CI)
      - name: Flutter build iOS (debug, no-codesign)
        script: |
          flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/iphoneos/**/*.app
      - build/ios/iphoneos/**/*.ipa
