workflows:
  ios-debug:
    name: iOS debug build (patch AR engine)
    environment:
      flutter: stable
      xcode: latest

    scripts:
      # 1️⃣ Clean & fetch packages
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      # 2️⃣ Ensure the Podfile adds GLTFSceneKit
      - name: Inject GLTFSceneKit pod
        script: |
          PODFILE_PATH="ios/Podfile"
          if ! grep -q "pod 'GLTFSceneKit'" "$PODFILE_PATH"; then
            echo "Adding pod 'GLTFSceneKit' to Podfile"
            awk '/target .Runner./ && c==0 {print "  pod '\''GLTFSceneKit'\''"; c=1}1' "$PODFILE_PATH" > "$PODFILE_PATH.tmp"
            mv "$PODFILE_PATH.tmp" "$PODFILE_PATH"
          fi

      # 3️⃣ 🩹  Create podspec for ar_flutter_plugin_engine (with dependency)
      - name: Patch ar_flutter_plugin_engine podspec
        script: |
          set -e
          CACHE_DIR=$(find "$HOME/.pub-cache" -type d -name "ar_flutter_plugin_engine-*" | head -n 1)
          mkdir -p "$CACHE_DIR/ios"
          PODSPEC_PATH="$CACHE_DIR/ios/ar_flutter_plugin_engine.podspec"
          if [ ! -f "$PODSPEC_PATH" ]; then
            printf '%s\n' \
              "Pod::Spec.new do |s|" \
              "  s.name    = 'ar_flutter_plugin_engine'" \
              "  s.version = '1.0.1'" \
              "  s.summary = 'ARKit/ARCore Flutter plugin (engine fork)'" \
              "  s.homepage= 'https://pub.dev/packages/ar_flutter_plugin_engine'" \
              "  s.license = { :type => 'MIT' }" \
              "  s.author  = { :name => 'Community' }" \
              "  s.source  = { :path => '.' }" \
              "  s.source_files = 'Classes/**/*.{h,m,mm,swift}'" \
              "  s.public_header_files = 'Classes/**/*.h'" \
              "  s.dependency 'Flutter'" \
              "  s.dependency 'GLTFSceneKit'" \
              "  s.platform = :ios, '12.0'" \
              "end" > "$PODSPEC_PATH"
          fi
          # copy into .symlinks, which podhelper will recreate
          SYMLINK_DIR="ios/.symlinks/plugins/ar_flutter_plugin_engine/ios"
          mkdir -p "$SYMLINK_DIR"
          cp -f "$PODSPEC_PATH" "$SYMLINK_DIR/"

      # 4️⃣ CocoaPods install
      - name: CocoaPods install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 5️⃣ Build (no codesign)
      - name: Flutter build iOS (debug, no-codesign)
        script: |
          flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/iphoneos/**/*.app
      - build/ios/iphoneos/**/*.ipa
